=== os2display/display-api-service/assets/shared/template/image-text/image-text-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/os2display/display-templates/blob/develop/build/image-text/image-text-schema.json",
  "title": "image-text schema",
  "description": "Content schema for image-text",
  "type": "object",
  "properties": {
    "image": {
      "description": "@id for the image",
      "type": "string"
    },
    "styling": {
      "type": "object",
      "properties": {
        "halfSize": {
          "description": "TODO: Describe",
          "type": "boolean"
        },
        "shadow": {
          "description": "TODO: Describe",
          "type": "boolean"
        },
        "boxAlign": {
          "description": "TODO: Describe",
          "type": "string"
        },
        "boxMargin": {
          "description": "TODO: Describe",
          "type": "boolean"
        },
        "separator": {
          "description": "TODO: Describe",
          "type": "boolean"
        },
        "reversed": {
          "description": "TODO: Describe",
          "type": "boolean"
        }
      }
    },
    "text": {
      "description": "Text for the slide",
      "type": "string"
    },
    "title": {
      "description": "Title for the slide",
      "type": "string"
    }
  }
}

=== os2display/display-api-service/assets/shared/template/image-text/image-text-content-example.json
{
  "title": "Slide title",
  "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...",
  "image": "/v1/media/00000000000000000000000001",
  "styling": {
    "boxAlign": "top",
    "boxMargin": false,
    "shadow": true,
    "separator": false,
    "halfSize": false,
    "reversed": false
  }
}
