=== os2display/display-api-service/assets/shared/template/book-review/book-review-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/os2display/display-templates/blob/develop/build/book-review/book-review-schema.json",
  "title": "book-review schema",
  "description": "Content schema for book-review",
  "type": "object",
  "properties": {
    "bookImage": {
      "description": "@id for the media for the review",
      "type": "string"
    },
    "authorImage": {
      "description": "@id for the media for the author",
      "type": "string"
    },
    "bookText": {
      "description": "Review rich text",
      "type": "string"
    },
    "authorText": {
      "description": "Author text",
      "type": "string"
    }
  }
}

=== os2display/display-api-service/assets/shared/template/book-review/book-review-content-example.json
{
  "bookText": "<h1>Lorem Ipsum</h1>...Is simply <strong>dummy text</strong> of the printing and typesetting industry...",
  "authorText": "There are many variations of passages of Lorem Ipsum available.",
  "authorImage": "/v1/media/00000000000000000000000001",
  "bookImage": "/v1/media/00000000000000000000000002"
}
